"""Mako template for migration scripts."""

"""Add email settings table

Revision ID: b34c6205a914
Revises: f4g5h6i7j8k9
Create Date: 2026-01-18 20:13:25.119457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34c6205a914'
down_revision = 'f4g5h6i7j8k9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sendgrid_api_key', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('blocked_image_domains_domain_key'), 'blocked_image_domains', type_='unique')
    op.drop_index(op.f('ix_blocked_image_domains_domain'), table_name='blocked_image_domains')
    op.create_index(op.f('ix_blocked_image_domains_domain'), 'blocked_image_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_blocked_image_domains_id'), 'blocked_image_domains', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False)

    # Initialize default email settings
    op.execute(
        "INSERT INTO email_settings (id, sendgrid_api_key, admin_email, updated_at) "
        "VALUES (1, NULL, 'admin@mealplanner.local', NOW())"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_blocked_image_domains_id'), table_name='blocked_image_domains')
    op.drop_index(op.f('ix_blocked_image_domains_domain'), table_name='blocked_image_domains')
    op.create_index(op.f('ix_blocked_image_domains_domain'), 'blocked_image_domains', ['domain'], unique=False)
    op.create_unique_constraint(op.f('blocked_image_domains_domain_key'), 'blocked_image_domains', ['domain'], postgresql_nulls_not_distinct=False)
    op.drop_table('email_settings')
    # ### end Alembic commands ###
