"""add_recipe_collections

Revision ID: b660a0cf8da0
Revises: 8b2d4e7f9012
Create Date: 2026-01-02 10:38:26.819990

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b660a0cf8da0"
down_revision = "8b2d4e7f9012"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_collections_id"), "recipe_collections", ["id"], unique=False)
    op.create_table(
        "recipe_collection_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["recipe_collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "recipe_id", name="uq_collection_recipe"),
    )
    op.create_index(
        op.f("ix_recipe_collection_items_id"), "recipe_collection_items", ["id"], unique=False
    )
    op.drop_index(op.f("ix_calendars_visibility"), table_name="calendars")
    op.drop_constraint(op.f("feature_toggles_feature_key_key"), "feature_toggles", type_="unique")
    op.create_index(op.f("ix_feature_toggles_id"), "feature_toggles", ["id"], unique=False)
    op.drop_index(op.f("ix_grocery_lists_visibility"), table_name="grocery_lists")
    op.drop_index(op.f("ix_recipes_visibility"), table_name="recipes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_recipes_visibility"), "recipes", ["visibility"], unique=False)
    op.create_index(
        op.f("ix_grocery_lists_visibility"), "grocery_lists", ["visibility"], unique=False
    )
    op.drop_index(op.f("ix_feature_toggles_id"), table_name="feature_toggles")
    op.create_unique_constraint(
        op.f("feature_toggles_feature_key_key"),
        "feature_toggles",
        ["feature_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_calendars_visibility"), "calendars", ["visibility"], unique=False)
    op.drop_index(op.f("ix_recipe_collection_items_id"), table_name="recipe_collection_items")
    op.drop_table("recipe_collection_items")
    op.drop_index(op.f("ix_recipe_collections_id"), table_name="recipe_collections")
    op.drop_table("recipe_collections")
    # ### end Alembic commands ###
