"""add checkout urls to kroger settings

Revision ID: l2m3n4o5p6q7
Revises: 38f5ae7ce5d4
Create Date: 2026-01-19 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'l2m3n4o5p6q7'
down_revision = '38f5ae7ce5d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kroger_settings', sa.Column('checkout_url', sa.String(length=500), nullable=True))
    op.add_column('kroger_settings', sa.Column('certification_checkout_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kroger_settings', 'certification_checkout_url')
    op.drop_column('kroger_settings', 'checkout_url')
    # ### end Alembic commands ###
